"use client";

import type { Supplier, WorkspaceTabProps } from "../../lib/workspace-types";

export type WorkspaceFeatureSliceArgs = {
  ui: any;
  runtime: any;
  data: any;
  mutations: any;
  derived: any;
  modalActions: any;
  featureState?: any;
  featureMutations?: any;
  featureData?: any;
  toast: (type: "ok" | "err" | "info", msg: string) => void;
  approvalMeta?: any;
  BF: any;
  chipRL: any;
  sevChip: (severity: string) => any;
  cStatusChip: (status: string) => any;
  aStatusChip: (status: string) => any;
  pChip: (priority: string) => any;
  dueBadge: (dueDate?: string | null) => any;
  RiskBreakdown: ({ sup, compact }: { sup: Supplier; compact?: boolean }) => any;
};

export default function buildWorkspaceBaseCtx({
  ui,
  runtime,
  data,
  mutations,
  derived,
  modalActions,
  featureState,
  featureMutations,
  toast,
  approvalMeta,
  BF,
  chipRL,
  sevChip,
  cStatusChip,
  aStatusChip,
  pChip,
  dueBadge,
  RiskBreakdown,
}: WorkspaceFeatureSliceArgs): WorkspaceTabProps {
  return {
    L: ui.L,
    company: data.company,
    suppliers: data.suppliers,
    complaints: data.complaints,
    actions: data.actions,
    events: data.events,
    screenings: data.screenings,
    loading: data.loading,
    expanded: featureState?.suppliers?.expanded ?? ui.expanded,
    editingSup: featureState?.suppliers?.supplierForm?.editingSup ?? ui.editingSup,
    sName: featureState?.suppliers?.supplierForm?.sName ?? ui.sName,
    setSName: featureState?.suppliers?.supplierForm?.setSName ?? ui.setSName,
    sCountry: featureState?.suppliers?.supplierForm?.sCountry ?? ui.sCountry,
    setSCountry: featureState?.suppliers?.supplierForm?.setSCountry ?? ui.setSCountry,
    sInd: featureState?.suppliers?.supplierForm?.sInd ?? ui.sInd,
    setSInd: featureState?.suppliers?.supplierForm?.setSInd ?? ui.setSInd,
    csv: featureState?.suppliers?.supplierForm?.csv ?? ui.csv,
    setCsv: featureState?.suppliers?.supplierForm?.setCsv ?? ui.setCsv,
    showCapModal: ui.showCapModal,
    setShowCapModal: ui.setShowCapModal,
    capPara: ui.capPara,
    setCapPara: ui.setCapPara,
    triageRes: featureState?.complaints?.triage?.triageRes ?? ui.triageRes,
    setTriageRes: featureState?.complaints?.triage?.setTriageRes ?? ui.setTriageRes,
    triageLd: featureState?.complaints?.triage?.triageLd ?? ui.triageLd,
    actionNotes: ui.actionNotes,
    setActionNotes: ui.setActionNotes,
    supAI: ui.supAI,
    supCAP: ui.supCAP,
    supLd: ui.supLd,
    rYear: featureState?.reports?.reports?.rYear ?? runtime.rYear,
    setRYear: featureState?.reports?.reports?.setRYear ?? runtime.setRYear,
    draft: featureState?.reports?.reports?.draft ?? runtime.draft,
    setDraft: featureState?.reports?.reports?.setDraft ?? runtime.setDraft,
    draftTs: featureState?.reports?.reports?.draftTs ?? runtime.draftTs,
    genLd: featureState?.reports?.reports?.genLd ?? runtime.genLd,
    aiMsgs: featureState?.reports?.ai?.aiMsgs ?? runtime.aiMsgs,
    setAiMsgs: featureState?.reports?.ai?.setAiMsgs ?? runtime.setAiMsgs,
    aiInput: featureState?.reports?.ai?.aiInput ?? runtime.aiInput,
    setAiInput: featureState?.reports?.ai?.setAiInput ?? runtime.setAiInput,
    aiLd: featureState?.reports?.ai?.aiLd ?? runtime.aiLd,
    saqs: data.saqs,
    saqEmail: runtime.saqEmail,
    setSaqEmail: runtime.setSaqEmail,
    saqSup: runtime.saqSup,
    setSaqSup: runtime.setSaqSup,
    saqDays: runtime.saqDays,
    setSaqDays: runtime.setSaqDays,
    saqSending: runtime.saqSending,
    kpiLive: data.kpiLive,
    kpiTrend: data.kpiTrend,
    kpiLd: runtime.kpiLd,
    supFilter: featureState?.suppliers?.supFilter ?? ui.supFilter,
    setSupFilter: featureState?.suppliers?.setSupFilter ?? ui.setSupFilter,
    auditLog: data.auditLog,
    auditFilter: runtime.auditFilter,
    setAuditFilter: runtime.setAuditFilter,
    auditLd: data.auditLd,
    showQuickstart: ui.showQuickstart,
    evidences: data.evidences,
    evTitle: ui.evTitle,
    setEvTitle: ui.setEvTitle,
    evType: ui.evType,
    setEvType: ui.setEvType,
    evLksg: ui.evLksg,
    setEvLksg: ui.setEvLksg,
    evDesc: ui.evDesc,
    setEvDesc: ui.setEvDesc,
    evSupId: ui.evSupId,
    setEvSupId: ui.setEvSupId,
    evFile: ui.evFile,
    setEvFile: ui.setEvFile,
    evUploading: ui.evUploading,
    openAddSupModal: modalActions.openAddSupModal,
    openEditSupModal: modalActions.openEditSupModal,
    delSupplier: featureMutations?.suppliers?.delSupplier ?? mutations.delSupplier,
    recalc: featureMutations?.suppliers?.recalc ?? mutations.recalc,
    importCsv: featureMutations?.suppliers?.importCsv ?? mutations.importCsv,
    submitComplaint: featureMutations?.complaints?.submitComplaint ?? mutations.submitComplaint,
    triageComplaint: featureMutations?.complaints?.triageComplaint ?? mutations.triageComplaint,
    updateComplaintStatus: featureMutations?.complaints?.updateComplaintStatus ?? mutations.updateComplaintStatus,
    saveComplaintNote: featureMutations?.complaints?.saveComplaintNote ?? mutations.saveComplaintNote,
    createCap: mutations.createCap,
    updateActionStatus: mutations.updateActionStatus,
    saveActionNote: mutations.saveActionNote,
    deleteAction: mutations.deleteAction,
    loadDraft: featureMutations?.reports?.loadDraft ?? mutations.loadDraft,
    saveDraft: featureMutations?.reports?.saveDraft ?? mutations.saveDraft,
    genSection: featureMutations?.reports?.genSection ?? mutations.genSection,
    getSupAI: mutations.getSupAI,
    getSupCAP: mutations.getSupCAP,
    sendAi: featureMutations?.reports?.sendAi ?? mutations.sendAi,
    loadAuditLog: mutations.loadAuditLog,
    exportCSV: mutations.exportCSV,
    sendSaq: mutations.sendSaq,
    deleteSaq: mutations.deleteSaq,
    loadKpi: mutations.loadKpi,
    saveKpiSnapshot: mutations.saveKpiSnapshot,
    uploadEvidence: mutations.uploadEvidence,
    deleteEvidence: mutations.deleteEvidence,
    chipRL,
    sevChip,
    cStatusChip,
    aStatusChip,
    pChip,
    dueBadge,
    RiskBreakdown,
    setTab: runtime.setTab,
    fileRef: runtime.fileRef,
    score: derived.score,
    kpis: derived.kpis,
    actionStats: derived.actionStats,
    workspaceAssist: derived.workspaceAssist,
    BF,
    quickstartSteps: derived.quickstartSteps,
    quickstartDone: derived.quickstartDone,
    cSup: featureState?.complaints?.complaintForm?.cSup ?? ui.cSup,
    setCSup: featureState?.complaints?.complaintForm?.setCSup ?? ui.setCSup,
    cCat: featureState?.complaints?.complaintForm?.cCat ?? ui.cCat,
    setCCat: featureState?.complaints?.complaintForm?.setCCat ?? ui.setCCat,
    cSev: featureState?.complaints?.complaintForm?.cSev ?? ui.cSev,
    setCSev: featureState?.complaints?.complaintForm?.setCSev ?? ui.setCSev,
    cDesc: featureState?.complaints?.complaintForm?.cDesc ?? ui.cDesc,
    setCDesc: featureState?.complaints?.complaintForm?.setCDesc ?? ui.setCDesc,
    cNotes: featureState?.complaints?.complaintNotes?.cNotes ?? ui.cNotes,
    setCNotes: featureState?.complaints?.complaintNotes?.setCNotes ?? ui.setCNotes,
    toast,
    requestState: data.requestState.domains,
    reloads: data.reloads,
    approvalMeta: approvalMeta ? { pending: approvalMeta.pending, approved: approvalMeta.approved, rejected: approvalMeta.rejected, lastStatus: approvalMeta.lastStatus, loading: approvalMeta.loading, currentRole: approvalMeta.currentRole, canRequest: approvalMeta.canRequest, canApprove: approvalMeta.canApprove, draftLocked: approvalMeta.draftLocked, rows: approvalMeta.rows, notes: approvalMeta.notes, setNotes: approvalMeta.setNotes, loadApprovals: approvalMeta.loadApprovals, requestApproval: approvalMeta.requestApproval, reviewApproval: approvalMeta.reviewApproval } : { pending: 0, approved: 0, rejected: 0, lastStatus: "none", loading: false, currentRole: "viewer", canRequest: false, canApprove: false, draftLocked: false },
  };
}
